[package]
name = "au"
version = "0.0.1"
authors = ["Jens Nockert <jens@nockert.se>"]

[features]
complete-tests = []

[lib]
name = "au"
path = "src/au.rs"

[dependencies.aurora]
git = "https://github.com/audiocogs/aurora.rs"